version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bikeRentSystem
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uuser", "-ppassword"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "3307:3306"

  backend:
    build: .
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: bikeRentSystem
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  mysql-data: